name: agdourapp2
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  firebase_database: ^3.1.6
  flutter_spinkit: ^4.1.2+1
  mailer: ^3.0.3
  progress_dialog: ^1.2.0
  firebase_storage: ^3.1.1



  permission_handler: ^5.0.0+hotfix.4
  share: ^0.6.3+6
  rate_my_app: ^0.6.1+2
  adjust_sdk: ^4.21.0
  curved_navigation_bar: ^0.3.2
  google_maps_flutter: ^0.5.25+3
  geolocator: ^5.3.1
  provider: ^4.0.5
  url_launcher: ^5.4.2
  http: ^0.12.0+4
  flutter_rating_bar: ^3.0.1+1
  flutter_google_places: ^0.2.5
  location: ^3.0.2
  cupertino_icons: ^0.1.2
  humanitarian_icons: ^0.1.0
  font_awesome_flutter: ^8.2.0
  image_picker: ^0.5.3+1
  shared_preferences: ^0.5.7+2
  android_intent: ^0.3.7+2
  flutter_launcher_icons: ^0.7.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_share_me: ^0.9.1
  social_share: ^2.0.4
  social_share_plugin: ^0.3.1+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"







flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

     - assets/eme.jpg
     - assets/23.jpg
     - assets/ee.jpg
     - assets/pp.png
     - assets/oo.jpg
     - assets/pn.jpg
     - assets/ccal.png
     - assets/pic.jpg
     - assets/n.jpg
     - assets/ww.png
     - assets/caal.png
     - assets/amb.jpg
     - assets/mb.jpg
     - assets/logo.jpg
     - assets/icon.jpg
     - assets/errr.png






  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
